// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace MVCUI.Controllers
{
    public partial class _SharedItemController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected _SharedItemController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ContactUs()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ContactUs);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult _MetaTags()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames._MetaTags);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.JsonResult> subscribe()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.subscribe);
            return System.Threading.Tasks.Task.FromResult(callInfo as System.Web.Mvc.JsonResult);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public _SharedItemController Actions { get { return MVC._SharedItem; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "_SharedItem";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "_SharedItem";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string NavBar = "NavBar";
            public readonly string Menu = "Menu";
            public readonly string Search = "Search";
            public readonly string BelovedProducts = "BelovedProducts";
            public readonly string NewestProduct = "NewestProduct";
            public readonly string MoreSellProduct = "MoreSellProduct";
            public readonly string MoreVisitedProduct = "MoreVisitedProduct";
            public readonly string ProductSelected = "ProductSelected";
            public readonly string AboutUs = "AboutUs";
            public readonly string ContactUs = "ContactUs";
            public readonly string _MetaTags = "_MetaTags";
            public readonly string subscribe = "subscribe";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string NavBar = "NavBar";
            public const string Menu = "Menu";
            public const string Search = "Search";
            public const string BelovedProducts = "BelovedProducts";
            public const string NewestProduct = "NewestProduct";
            public const string MoreSellProduct = "MoreSellProduct";
            public const string MoreVisitedProduct = "MoreVisitedProduct";
            public const string ProductSelected = "ProductSelected";
            public const string AboutUs = "AboutUs";
            public const string ContactUs = "ContactUs";
            public const string _MetaTags = "_MetaTags";
            public const string subscribe = "subscribe";
        }


        static readonly ActionParamsClass_ContactUs s_params_ContactUs = new ActionParamsClass_ContactUs();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ContactUs ContactUsParams { get { return s_params_ContactUs; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ContactUs
        {
            public readonly string type = "type";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass__MetaTags s_params__MetaTags = new ActionParamsClass__MetaTags();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass__MetaTags _MetaTagsParams { get { return s_params__MetaTags; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass__MetaTags
        {
            public readonly string title = "title";
            public readonly string keywords = "keywords";
            public readonly string description = "description";
        }
        static readonly ActionParamsClass_subscribe s_params_subscribe = new ActionParamsClass_subscribe();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_subscribe subscribeParams { get { return s_params_subscribe; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_subscribe
        {
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _BelovedProducts = "_BelovedProducts";
                public readonly string _feature = "_feature";
                public readonly string _menu = "_menu";
                public readonly string _MetaTags = "_MetaTags";
                public readonly string _MoreSellProduct = "_MoreSellProduct";
                public readonly string _MoreVisit = "_MoreVisit";
                public readonly string _navbar = "_navbar";
                public readonly string _NewestProduct = "_NewestProduct";
                public readonly string _search = "_search";
                public readonly string _shoppingCard = "_shoppingCard";
                public readonly string _ShowProduct = "_ShowProduct";
                public readonly string ContactUs = "ContactUs";
                public readonly string ProductSelected = "ProductSelected";
            }
            public readonly string _BelovedProducts = "~/Views/_SharedItem/_BelovedProducts.cshtml";
            public readonly string _feature = "~/Views/_SharedItem/_feature.cshtml";
            public readonly string _menu = "~/Views/_SharedItem/_menu.cshtml";
            public readonly string _MetaTags = "~/Views/_SharedItem/_MetaTags.cshtml";
            public readonly string _MoreSellProduct = "~/Views/_SharedItem/_MoreSellProduct.cshtml";
            public readonly string _MoreVisit = "~/Views/_SharedItem/_MoreVisit.cshtml";
            public readonly string _navbar = "~/Views/_SharedItem/_navbar.cshtml";
            public readonly string _NewestProduct = "~/Views/_SharedItem/_NewestProduct.cshtml";
            public readonly string _search = "~/Views/_SharedItem/_search.cshtml";
            public readonly string _shoppingCard = "~/Views/_SharedItem/_shoppingCard.cshtml";
            public readonly string _ShowProduct = "~/Views/_SharedItem/_ShowProduct.cshtml";
            public readonly string ContactUs = "~/Views/_SharedItem/ContactUs.cshtml";
            public readonly string ProductSelected = "~/Views/_SharedItem/ProductSelected.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC__SharedItemController : MVCUI.Controllers._SharedItemController
    {
        public T4MVC__SharedItemController() : base(Dummy.Instance) { }

        [NonAction]
        partial void NavBarOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult NavBar()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.NavBar);
            NavBarOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void MenuOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.PartialViewResult> Menu()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.Menu);
            MenuOverride(callInfo);
            return System.Threading.Tasks.Task.FromResult(callInfo as System.Web.Mvc.PartialViewResult);
        }

        [NonAction]
        partial void SearchOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult Search()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.Search);
            SearchOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void BelovedProductsOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult BelovedProducts()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.BelovedProducts);
            BelovedProductsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void NewestProductOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult NewestProduct()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.NewestProduct);
            NewestProductOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void MoreSellProductOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult MoreSellProduct()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.MoreSellProduct);
            MoreSellProductOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void MoreVisitedProductOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult MoreVisitedProduct()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.MoreVisitedProduct);
            MoreVisitedProductOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ProductSelectedOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult ProductSelected()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.ProductSelected);
            ProductSelectedOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AboutUsOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult AboutUs()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.AboutUs);
            AboutUsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ContactUsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, DomainClasses.Enums.ContactType type);

        [NonAction]
        public override System.Web.Mvc.ActionResult ContactUs(DomainClasses.Enums.ContactType type)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ContactUs);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "type", type);
            ContactUsOverride(callInfo, type);
            return callInfo;
        }

        [NonAction]
        partial void ContactUsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ViewModel.ViewModel.Admin.ContactUs.ContactUsViewModel model);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> ContactUs(ViewModel.ViewModel.Admin.ContactUs.ContactUsViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ContactUs);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ContactUsOverride(callInfo, model);
            return System.Threading.Tasks.Task.FromResult(callInfo as System.Web.Mvc.ActionResult);
        }

        [NonAction]
        partial void _MetaTagsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string title, string keywords, string description);

        [NonAction]
        public override System.Web.Mvc.ActionResult _MetaTags(string title, string keywords, string description)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames._MetaTags);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "title", title);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "keywords", keywords);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "description", description);
            _MetaTagsOverride(callInfo, title, keywords, description);
            return callInfo;
        }

        [NonAction]
        partial void subscribeOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, ViewModel.ViewModel.Admin.Subscribe.SubscribeViewModel model);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.JsonResult> subscribe(ViewModel.ViewModel.Admin.Subscribe.SubscribeViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.subscribe);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            subscribeOverride(callInfo, model);
            return System.Threading.Tasks.Task.FromResult(callInfo as System.Web.Mvc.JsonResult);
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
